import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft, ArrowRight, ArrowUpRight, Check } from 'lucide-react';
import { projects } from '@/data/projects';
import { ProjectVisual } from '@/components/ProjectVisual';
import { BpaFlow, BpaArchitecture } from '@/components/BpaFlow';
export function generateStaticParams() { return projects.map(p => ({slug:p.slug})); }
export async function generateMetadata({ params }: {params: Promise<{slug:string}>}): Promise<Metadata> { const {slug} = await params; const project = projects.find(p => p.slug === slug); return {title: project?.name ?? 'Projeto não encontrado', description: project?.description, ...(process.env.NEXT_PUBLIC_SITE_URL ? {alternates: {canonical: `/projects/${slug}`}} : {})}; }
export default async function ProjectPage({params}: {params: Promise<{slug:string}>}) { const {slug} = await params; const project = projects.find(p=>p.slug===slug); if (!project) notFound(); const other = projects.find(p=>p.slug!==slug)!; return <main id="main" className="project-detail"><Link href="/#projetos" className="text-link"><ArrowLeft size={17}/>Todos os projetos</Link><p className="eyebrow">{project.category}</p><h1>{project.name}<span>.</span></h1><p className="detail-lead">{project.description}</p><div className="tags">{project.tags.map(t=><span key={t}>{t}</span>)}</div>{slug === 'bpa-analyzer' ? <BpaFlow/> : <ProjectVisual variant={project.icon}/>}<div className="detail-grid"><div><p className="eyebrow">VISÃO GERAL</p><h2>Da necessidade<br/><span>à proposta.</span></h2></div><div><p>{project.overview}</p><h3>O problema</h3><p>{project.problem}</p><h3>A solução</h3><p>{project.solution}</p></div></div>{slug === 'bpa-analyzer' ? <BpaArchitecture/> : (<section className="detail-section"><p className="eyebrow">ARQUITETURA CONCEITUAL</p><div className="architecture">{project.architecture.map((step,i)=><div key={step}><span>0{i+1}</span><h3>{step}</h3>{i<2 && <ArrowRight size={20}/>}</div>)}</div><p className="muted">Fluxo conceitual da proposta. Detalhes de implementação e integrações serão adicionados após a documentação técnica.</p></section>)}<div className="detail-grid"><div><p className="eyebrow">DIFERENCIAIS</p><h2>Foco no que<br/><span>precisa ser visto.</span></h2></div><div>{project.features.map(feature=><p className="feature" key={feature}><Check size={18}/>{feature}</p>)}<h3>Impacto esperado</h3><p>{project.impact}</p><h3>Conclusão</h3><p>Uma iniciativa para aproximar análise técnica e decisão, com uma experiência centrada na clareza das informações.</p></div></div><Link className="next-project" href={`/projects/${other.slug}`}><span>PRÓXIMO PROJETO<strong>{other.name}</strong></span><ArrowUpRight size={38}/></Link></main>; }

