import Image from 'next/image';
import Link from 'next/link';
import { ArrowDown, ArrowDownToLine, ArrowUpRight, ArrowRight, ChartNoAxesCombined, Database, Gauge, Figma, Workflow, Code2, Binary, ChartPie, Github, Linkedin, Mail, Phone } from 'lucide-react';
import { profile, technologies, experience, certifications, education } from '@/data/profile';
import { projects } from '@/data/projects';
import { ProjectVisual } from '@/components/ProjectVisual';
const expertise = [
 {icon: ChartNoAxesCombined, name: 'Power BI avançado', text: 'Dashboards e indicadores de performance para apoiar decisões estratégicas.'},
 {icon: Binary, name: 'DAX', text: 'Modelagem de cálculos e indicadores para análises em Power BI.'},
 {icon: ChartPie, name: 'Visuais customizados', text: 'Visualização de dados alinhada às necessidades do negócio.'},
 {icon: Gauge, name: 'Performance', text: 'Monitoramento do Power BI Service com foco em desempenho e redução de custos.'},
 {icon: Database, name: 'SQL Server', text: 'Nível intermediário em extração, consulta e análise de dados.'},
 {icon: Code2, name: 'Python', text: 'Competência em Python, com curso Python Hashtag concluído em janeiro de 2026.'},
 {icon: Figma, name: 'Figma', text: 'Ferramenta de design integrada às competências de visualização de dados.'},
 {icon: Workflow, name: 'Power Query M', text: 'Preparação, limpeza e transformação de dados com a linguagem M no Power Query.'},
];
export default function Home() { return <main id="main">
 <section className="hero" aria-labelledby="hero-title"><div className="hero-topline"><span><i/> PERSONAL DATA & ANALYTICS PORTFOLIO</span><span>ESTRATÉGIA · TECNOLOGIA · IMPACTO</span></div><div className="hero-content"><div className="hero-copy"><p className="eyebrow">OLÁ, EU SOU ANDERSON MURILO SANTOS</p><h1 id="hero-title">Transformando<br/>dados em<br/><span>decisões.</span><span className="title-dot">↗</span></h1><p className="hero-role">DataViz <span>/</span> Support Analytics</p><p className="hero-description">Mais de 16 anos em software e dados, conectando Power BI e visão de negócio às decisões estratégicas.</p><div className="hero-actions"><a className="button primary" href="#projetos">Explorar projetos <ArrowUpRight size={18}/></a><Link className="text-link" href="#contato">Falar comigo <ArrowRight size={17}/></Link></div></div><div className="hero-art"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="portrait-stage"><div className="portrait-disc" aria-hidden="true"/><div className="portrait-cutout"><Image src="/images/profile-cutout.png" alt="Anderson Murilo Santos, profissional de DataViz e Support Analytics" fill priority sizes="(max-width: 700px) 85vw, 480px"/></div></div></div></div><div className="hero-bottom"><a href="#sobre"><ArrowDown size={16}/> Explore o portfólio</a><span className="hero-summary">Da complexidade dos dados à clareza das decisões.</span></div></section>
 <section id="sobre" className="section about"><div><p className="eyebrow">01 / SOBRE MIM</p><h2>Visão de negócio.<br/><span>Profundidade técnica.</span></h2></div><div className="about-copy"><p>Sou Anderson Murilo Santos, profissional com <strong>mais de 16 anos de experiência em software e dados</strong>, formado em Gerenciamento de Redes e Telecomunicações e com MBA em Gestão de Projetos.</p><p>Atualmente atuo como DataViz, na sustentação do ambiente Power BI Service e na geração de insights com Power BI, apoiando a alta gestão em suas decisões estratégicas.</p><p>Visão de negócios, foco no cliente interno e externo, perfil autodidata e trabalho em equipe orientam minha atuação.</p><div className="about-signature"><span className="signature">Anderson Santos</span><span>DATA & ANALYTICS</span></div></div></section>
 <section id="especialidades" className="section"><div className="section-heading"><div><p className="eyebrow">02 / ESPECIALIDADES</p><h2>Do dado bruto.<br/><span>Ao próximo passo.</span></h2></div><p>Competências que se conectam para resolver<br className="desktop-break"/> desafios de ponta a ponta.</p></div><div className="expertise-grid">{expertise.map(({icon: Icon,name,text},i) => <article className="expertise-card" key={name}><div className="card-top"><Icon size={25} strokeWidth={1.4}/><span>0{i+1}</span></div><h3>{name}</h3><p>{text}</p></article>)}</div></section>
 <section id="projetos" className="section"><div className="section-heading"><div><p className="eyebrow">03 / PROJETOS SELECIONADOS</p><h2>Tecnologia aplicada.<br/><span>Propósito em cada projeto.</span></h2></div><span className="section-note">PORTFÓLIO TÉCNICO <ArrowDown size={17}/></span></div><div className="projects-grid">{projects.map((project,i) => <Link className="project-card" key={project.slug} href={`/projects/${project.slug}`}><div className="project-image-wrap"><span className="project-number">0{i+1}</span><ProjectVisual variant={project.icon}/><span className="project-open"><ArrowUpRight/></span></div><div className="project-info"><p className="eyebrow">{project.category}</p><h3>{project.name}</h3><p>{project.description}</p><div className="tags">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div></div></Link>)}</div></section>
 <section id="stack" className="section stack-section"><p className="eyebrow">04 / ECOSSISTEMA TÉCNICO</p><div className="section-heading"><h2>As ferramentas.<br/><span>As possibilidades.</span></h2><p>Tecnologias que conectam<br/>dados, pessoas e soluções.</p></div><div className="technology-list">{technologies.map((name,i) => <span key={name}><span className="tech-index">{String(i+1).padStart(2,'0')}</span>{name}<ArrowUpRight size={15}/></span>)}</div></section>
 <section id="experiencia" className="section career"><div><p className="eyebrow">05 / TRAJETÓRIA</p><h2>Conhecimento<br/><span>em evolução.</span></h2><p className="muted">Mais de 16 anos de experiência em software e dados.</p><p className="muted">CNH — Categoria B</p></div><div className="career-content"><h3>Experiência profissional</h3><div className="career-timeline">{experience.map(item => <article className="career-entry" key={item.company}><small>{item.period}</small><h4>{item.role}</h4><span className="career-company">{item.company}</span><p>{item.description}</p></article>)}</div><h3>Formação acadêmica</h3>{education.map(item => <article className="credential" key={item.name}><h4>{item.name}</h4><p>{item.institution}{item.period && ` · ${item.period}`}</p></article>)}<h3>Cursos & certificações</h3>{certifications.map(item => <article className="credential" key={item.name}><h4>{item.url ? <a href={item.url} target="_blank" rel="noreferrer">{item.name} ↗</a> : item.name}</h4><p>{item.issuer}{item.date && ` · ${item.date}`}</p></article>)}{profile.cv && <a className="text-link" href={profile.cv} download>Baixar currículo <ArrowDownToLine size={18}/></a>}</div></section>
 <section id="contato" className="contact-section"><p className="eyebrow">06 / VAMOS CONVERSAR</p><h2>Seu próximo desafio.<br/><span>Uma nova possibilidade.</span></h2><p>Vamos conectar dados, ideias e objetivos de negócio.</p><div className="contact-links"><a className="button secondary" href={profile.phoneHref}><Phone size={18}/>{profile.phone}</a>{profile.email && <a className="button primary" href={`mailto:${profile.email}`}><Mail size={18}/>{profile.email} <ArrowUpRight size={18}/></a>}{profile.linkedin && <a className="button secondary" href={profile.linkedin} target="_blank" rel="noreferrer"><Linkedin size={18}/>LinkedIn <ArrowUpRight size={18}/></a>}<a className="button secondary" href={profile.github} target="_blank" rel="noreferrer"><Github size={18}/>GitHub <ArrowUpRight size={18}/></a></div><span className="contact-decoration" aria-hidden="true">↗</span></section>
 </main>; }






