import { FlowMotion } from './FlowMotion';
import { Cloud, Download, ArrowDown, ArrowRight, FileInput, ScanLine, PanelsTopLeft, Network, FileCode2, ChartNoAxesCombined } from 'lucide-react';
const stages = [
 { title: 'Preparação', icon: FileInput, short: 'Arquivo + regras', description: 'Seleciona o arquivo PBIX/PBIT e as regras BPA padrão ou por cliente. O backend prepara a execução com Power BI Desktop e Tabular Editor Portable.' },
 { title: 'Análise BPA', icon: ScanLine, short: 'Modelo semântico', description: 'O Power BI Desktop disponibiliza o modelo via Analysis Services local. O Tabular Editor aplica as regras de boas práticas e o backend normaliza as violações.' },
 { title: 'Análise BPA Visual', icon: PanelsTopLeft, short: 'Páginas e visuais', description: 'Extrai e normaliza o layout do relatório, identifica regras compatíveis e avalia páginas e visuais. As violações visuais têm histórico próprio, separado dos indicadores do BPA semântico.' },
 { title: 'Colunas e medidas', icon: Network, short: 'Uso e dependências', description: 'Cruza o uso nos visuais com dependências DAX e metadados do modelo. Identifica objetos não utilizados e usados apenas por não utilizados, respeitando proteções estruturais e casos de revisão manual.' },
 { title: 'Documentação HTML', icon: FileCode2, short: 'Opcional · sob confirmação', description: 'Após as análises, o usuário decide se deseja gerar a documentação. Scripts C# executados no Tabular Editor consolidam metadados em um relatório HTML autocontido.' },
 { title: 'Exportação da documentação', icon: Download, short: 'Download do HTML', description: 'Permite baixar a documentação HTML gerada a partir do histórico de documentação, para consulta e compartilhamento fora da aplicação.' },
 { title: 'Resultados e histórico', icon: ChartNoAxesCombined, short: 'Revisão técnica', description: 'Disponibiliza violações, dashboards, históricos e exportações para apoiar a revisão técnica. Os resultados dos módulos permanecem organizados em seus respectivos históricos.' },
];
const online = { title: 'Análise BPA On-line', icon: Cloud, description: 'Conecta ao modelo semântico publicado no Power BI/Fabric por endpoint XMLA e executa regras com o Tabular Editor Portable, sem arquivo PBIX/PBIT local. Requer autenticação e permissões de acesso. Os resultados e a exportação HTML on-line são isolados das análises locais.' };
export function BpaFlow() { return <figure className="bpa-flow" aria-labelledby="bpa-flow-title"><figcaption><span className="eyebrow">DA ENTRADA AO DIAGNÓSTICO</span><h2 id="bpa-flow-title">Como o BPA Analyzer opera</h2><p>Análise local com pipeline assistido e análise on-line por XMLA.</p></figcaption><div className="bpa-online-path"><Cloud size={26} aria-hidden="true"/><div><h3>Análise BPA On-line · caminho independente</h3><p>Power BI / Fabric → conexão XMLA → regras BPA → resultados e exportação HTML on-line</p></div></div><p className="eyebrow">PIPELINE LOCAL · PBIX / PBIT</p><FlowMotion><ol className="bpa-flow-track">{stages.map(({title,short,icon:Icon},i)=><li key={title}><span className="flow-number">{String(i+1).padStart(2,'0')}</span><Icon size={27} strokeWidth={1.4} aria-hidden="true"/><h3>{title}</h3><p>{short}</p>{i<stages.length-1 && <ArrowRight className="flow-arrow" size={20} aria-hidden="true"/>}</li>)}</ol></FlowMotion><div className="flow-note"><ArrowDown size={16} aria-hidden="true"/><p>O BPA é a etapa inicial. No pipeline, BPA Visual e análise de uso avançam após sucesso da etapa anterior. A documentação HTML depende da escolha do usuário e pode ser baixada após a geração. O caminho on-line não executa automaticamente as etapas visuais do pipeline local.</p></div></figure>; }
export function BpaArchitecture() { return <section className="detail-section"><p className="eyebrow">ARQUITETURA CONCEITUAL</p><h2>Uma visão de cada etapa.</h2><p className="muted">A interface React coordena o fluxo com um backend local Node.js, em uma aplicação desktop Electron. Power BI Desktop e Tabular Editor Portable dão suporte à análise do modelo.</p><div className="bpa-stage-grid">{[stages[0], stages[1], online, ...stages.slice(2)].map(({title,description,icon:Icon},i)=><article className="bpa-stage-card" key={title}><div><span>{String(i+1).padStart(2,'0')}</span><Icon size={24} strokeWidth={1.4} aria-hidden="true"/></div><h3>{title}</h3><p>{description}</p></article>)}</div><p className="muted">As etapas também podem ser executadas individualmente. Uma falha interrompe o avanço automático do pipeline; as demais etapas continuam disponíveis para execução manual.</p></section>; }


